In [69]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [145]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [3]:
torch.__version__

'2.0.1+cu117'

In [4]:
a = np.ones((2, 3))
b = torch.tensor(a)

a.dtype, b.dtype

(dtype('float64'), torch.float64)

In [5]:
a = np.ones((2, 3), dtype='float32')
b = torch.tensor(a)

a.dtype, b.dtype

(dtype('float32'), torch.float32)

In [7]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [8]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32, device=device)
x

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0', dtype=torch.int32)

In [9]:
a = torch.tensor([1, 2, 3, 4, 5])
a[0], a[-1]

(tensor(1), tensor(5))

In [10]:
a.size(), a.shape

(torch.Size([5]), torch.Size([5]))

In [14]:
a.dim(), a.ndimension(), a.ndim

(1, 1, 1)

In [15]:
a.view(5, 1), a.reshape(5, 1)

(tensor([[1],
         [2],
         [3],
         [4],
         [5]]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5]]))

In [17]:
a = torch.FloatTensor([0, 1, 2, 3, 4, 5])
a

tensor([0., 1., 2., 3., 4., 5.])

In [21]:
a = torch.cuda.FloatTensor([0, 1, 2, 3, 4, 5])
a

tensor([0., 1., 2., 3., 4., 5.], device='cuda:0')

In [23]:
a = a.type(torch.FloatTensor)
a

tensor([0., 1., 2., 3., 4., 5.])

In [24]:
b = a.to(device)
b

tensor([0., 1., 2., 3., 4., 5.], device='cuda:0')

In [26]:
b = a.cuda()
b

tensor([0., 1., 2., 3., 4., 5.], device='cuda:0')

In [27]:
c = a.type(torch.cuda.FloatTensor)
c

tensor([0., 1., 2., 3., 4., 5.], device='cuda:0')

In [28]:
d = b.to('cpu')
d

tensor([0., 1., 2., 3., 4., 5.])

In [29]:
e = c.cpu()
e

tensor([0., 1., 2., 3., 4., 5.])

In [30]:
x = torch.rand(5, 3)
x

tensor([[0.9833, 0.7262, 0.1248],
        [0.0277, 0.9861, 0.7827],
        [0.0787, 0.1217, 0.8319],
        [0.7123, 0.4820, 0.0333],
        [0.6466, 0.1875, 0.7878]])

In [31]:
x = torch.zeros(5, 3, dtype=torch.long)
x.dtype, x 

(torch.int64,
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]))

In [32]:
a = torch.tensor([7, 4, 3, 2, 6])
a.type(), a.dtype

('torch.LongTensor', torch.int64)

In [33]:
b = torch.FloatTensor([7, 4, 3, 2, 6])
b.type(), b.dtype

('torch.FloatTensor', torch.float32)

In [34]:
a == b

tensor([True, True, True, True, True])

In [35]:
all(a == b)

True

In [39]:
c = torch.tensor([7, 4, 3, 2, 6], dtype=torch.int64)
c, c.dtype

(tensor([7, 4, 3, 2, 6]), torch.int64)

In [41]:
d = torch.LongTensor([7, 4, 3, 2, 6])
d, d.dtype

(tensor([7, 4, 3, 2, 6]), torch.int64)

In [42]:
c == d, all(c == d)

(tensor([True, True, True, True, True]), True)

In [43]:
a = torch.Tensor([0, 1, 2, 3, 4])
a.size(), a.shape

(torch.Size([5]), torch.Size([5]))

In [45]:
a.dim(), a.ndimension()

(1, 1)

In [46]:
a, a.view(5, 1), a.reshape(5, 1)

(tensor([0., 1., 2., 3., 4.]),
 tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.]]),
 tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.]]))

In [47]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [49]:
x = torch.randn(4, 4)
x

tensor([[-0.9847,  0.9570,  0.1515, -0.6296],
        [ 1.4776, -1.0331,  1.7781,  0.2895],
        [ 1.2461,  0.7952,  0.2107,  1.6564],
        [-0.0999,  0.8482, -0.3023, -2.3740]])

In [50]:
x.is_contiguous()

True

In [51]:
x.transpose(0, 1)

tensor([[-0.9847,  1.4776,  1.2461, -0.0999],
        [ 0.9570, -1.0331,  0.7952,  0.8482],
        [ 0.1515,  1.7781,  0.2107, -0.3023],
        [-0.6296,  0.2895,  1.6564, -2.3740]])

In [52]:
x.transpose(0, 1).is_contiguous()

False

In [53]:
x.transpose(0, 1).reshape(-1, 8)

tensor([[-0.9847,  1.4776,  1.2461, -0.0999,  0.9570, -1.0331,  0.7952,  0.8482],
        [ 0.1515,  1.7781,  0.2107, -0.3023, -0.6296,  0.2895,  1.6564, -2.3740]])

In [54]:
x.transpose(0, 1).view(-1, 8)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [59]:
numpy_array = np.array([0., 1., 2., 3., 4., 5.])
torch_tensor = torch.from_numpy(numpy_array)
torch_tensor

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [60]:
back_to_numpy = torch_tensor.numpy()
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [61]:
numpy_array, torch_tensor, back_to_numpy

(array([0., 1., 2., 3., 4., 5.]),
 tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64),
 array([0., 1., 2., 3., 4., 5.]))

In [63]:
back_to_numpy[0] = 100

numpy_array, torch_tensor, back_to_numpy

(array([100.,   1.,   2.,   3.,   4.,   5.]),
 tensor([100.,   1.,   2.,   3.,   4.,   5.], dtype=torch.float64),
 array([100.,   1.,   2.,   3.,   4.,   5.]))

In [65]:
x = torch.randn(1)
x, x.item()

(tensor([1.5915]), 1.5914652347564697)

In [66]:
a = torch.tensor([5., 3., 4., 1.])
print(a[0])
print(a[0].item())

tensor(5.)
5.0


In [67]:
x = torch.randn(2)
x, x.numpy()

(tensor([ 0.0455, -0.8924]), array([ 0.04546148, -0.8924473 ], dtype=float32))

In [70]:
pandas_seris = pd.Series([.1, .2, .3, 10.1])
pandas_to_torch = torch.from_numpy(pandas_seris.values)
pandas_to_torch

tensor([ 0.1000,  0.2000,  0.3000, 10.1000], dtype=torch.float64)

In [71]:
this_tensor = torch.tensor([0, 1, 2, 3])
torch_to_list = this_tensor.tolist()
torch_to_list

[0, 1, 2, 3]

In [72]:
this_tensor.numpy()

array([0, 1, 2, 3])

In [73]:
c = torch.tensor([20, 1, 2, 3, 4])
c[0] = 100
c[4] = 0
c, c.dtype

(tensor([100,   1,   2,   3,   0]), torch.int64)

In [74]:
d = c[1:4]
d

tensor([1, 2, 3])

In [75]:
c[3:5] = torch.tensor([300., 400.])
c

tensor([100,   1,   2, 300, 400])

In [76]:
u = torch.tensor([1., 0.])
v = torch.tensor([.0, 1.])
z = u + v
z

tensor([1., 1.])

In [77]:
z = u - v
z

tensor([ 1., -1.])

In [78]:
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = u * v
z

tensor([3, 4])

In [79]:
y = torch.tensor([1, 2])
z = 2 * y
z

tensor([2, 4])

In [81]:
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = torch.dot(u, v)
z

tensor(7)

In [82]:
u = torch.tensor([1, 2, 3, -1])
z = u + 1
z

tensor([2, 3, 4, 0])

In [83]:
a = torch.tensor([1, -2, 3, 4, 5], dtype=torch.float32)
a.mean(), a.max(), a.std()

(tensor(2.2000), tensor(5.), tensor(2.7749))

In [84]:
np_linspace = np.linspace(-2, 2, 5)
np_linspace

array([-2., -1.,  0.,  1.,  2.])

In [85]:
torch_linspace = torch.linspace(-2, 2, 5)
torch_linspace

tensor([-2., -1.,  0.,  1.,  2.])

In [86]:
torch.linspace(10, 20, 10)

tensor([10.0000, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778,
        18.8889, 20.0000])

In [87]:
np.arange(-100, 100, 0.1)

array([-100. ,  -99.9,  -99.8, ...,   99.7,   99.8,   99.9])

In [88]:
torch.arange(-100, 100, 0.1)

tensor([-100.0000,  -99.9000,  -99.8000,  ...,   99.7000,   99.8000,
          99.9000])

In [89]:
_2d_tensor = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
_2d_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])

In [90]:
_2d_tensor.ndimension(), _2d_tensor.shape, _2d_tensor.size(), _2d_tensor.numel()

(2, torch.Size([4, 3]), torch.Size([4, 3]), 12)

In [91]:
x = torch.tensor([[1, 0], [0, 1]])
y = torch.tensor([[2, 1], [1, 2]])

x, y

(tensor([[1, 0],
         [0, 1]]),
 tensor([[2, 1],
         [1, 2]]))

In [92]:
x * y

tensor([[2, 0],
        [0, 2]])

In [146]:
x = torch.tensor([[0, 1, 1], [1, 0, 1]])
y = torch.tensor([[1, 1], [1, 1], [-1, 1]])
x, y

(tensor([[0, 1, 1],
         [1, 0, 1]]),
 tensor([[ 1,  1],
         [ 1,  1],
         [-1,  1]]))

In [149]:
torch.matmul(x, y), torch.mm(x, y), x @ y

(tensor([[0, 2],
         [0, 2]]),
 tensor([[0, 2],
         [0, 2]]),
 tensor([[0, 2],
         [0, 2]]))

In [95]:
np.matmul(x.numpy(), y.numpy())

array([[0, 2],
       [0, 2]])

In [96]:
x_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
x_1, x_2

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [100]:
[x_1, x_2]

[tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]])]

In [98]:
torch.cat([x_1, x_2])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [101]:
torch.cat([x_1, x_2], axis=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

In [102]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
x.shape, x

(torch.Size([2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [103]:
torch.sum(x)

tensor(21)

In [104]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [105]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [108]:
torch.max(x, axis=0), torch.min(x, axis=0)

(torch.return_types.max(
 values=tensor([4, 5, 6]),
 indices=tensor([1, 1, 1])),
 torch.return_types.min(
 values=tensor([1, 2, 3]),
 indices=tensor([0, 0, 0])))

In [109]:
torch.max(x, axis=1), torch.min(x, axis=1)

(torch.return_types.max(
 values=tensor([3, 6]),
 indices=tensor([2, 2])),
 torch.return_types.min(
 values=tensor([1, 4]),
 indices=tensor([0, 0])))

In [112]:
x, torch.argmax(x), torch.argmin(x)

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor(5),
 tensor(0))

In [116]:
torch.argmax(x, axis=0), torch.argmin(x, axis=0)

(tensor([1, 1, 1]), tensor([0, 0, 0]))

In [115]:
torch.argmax(x, axis=1), torch.argmin(x, axis=1)

(tensor([2, 2]), tensor([0, 0]))

In [121]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [122]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [123]:
y.backward()
x.grad

tensor(4.)

In [124]:
u = torch.tensor(1., requires_grad=True)
v = torch.tensor(2., requires_grad=True)
f = u * v + u ** 2
f

tensor(3., grad_fn=<AddBackward0>)

In [125]:
f.backward()

In [126]:
u.grad, v.grad

(tensor(4.), tensor(1.))

In [134]:
import torch

x = torch.ones(5) # input
y = torch.zeros(3) # expected output

w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)

z = torch.matmul(x, w) + b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss

tensor(0.3506, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [135]:
loss.backward()
w.grad, b.grad

(tensor([[0.0389, 0.1528, 0.0899],
         [0.0389, 0.1528, 0.0899],
         [0.0389, 0.1528, 0.0899],
         [0.0389, 0.1528, 0.0899],
         [0.0389, 0.1528, 0.0899]]),
 tensor([0.0389, 0.1528, 0.0899]))

In [136]:
z = torch.matmul(x, w) + b
z.requires_grad

True

In [137]:
with torch.inference_mode():
    z = torch.matmul(x, w) + b
z.requires_grad

False

In [138]:
z = torch.matmul(x, w) + b
z_det = z.detach()
z.requires_grad, z_det.requires_grad, 

(True, False)

In [139]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [140]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [141]:
x = x.to(device)
x

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [144]:
y = torch.ones(2, 3, device=device)
y

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')